<?php

return [
    'typeOfComponents' => [
        'processors'           => 'Процессоры',
        'motherboards'         => 'Материнские платы',
        'coolers'              => 'Кулеры',
        'storages'             => 'Хранилища',
        'random_access_memory' => 'Оперативная память',
        'videocards'           => 'Видеокарты',
        'psu'                  => 'Блоки питания',
        'cases'                => 'Корпусы',
    ],
    'dataOfComponents' => [
        'processors'           => [
            'title'                   => 'Название',
            'description'             => 'Описание',
            'tdp'                     => 'Тепловыделение',
            'base_frequency'          => 'Базовая частота',
            'max_frequency'           => 'Максимальная частота',
            'count_of_cores'          => 'Количество ядер',
            'count_of_streams'        => 'Количество потоков',
            'processor_generation_id' => 'Поколение процессоров',
            'socket_id'               => 'Сокет',
            'vendor_id'               => 'Производитель',
        ],
        'motherboards'         => [
            'title'              => 'Название',
            'subtitle'           => 'Доп. название',
            'description'        => 'Описание',
            'socket_id'          => 'Сокет',
            'chipset_id'         => 'Чипсет',
            'form_id'            => 'Форм-фактор',
            'express_version_id' => 'Версия PCI-E',
            'type_of_memory_id'  => 'Тип памяти',
            'vendor_id'          => 'Производитель',
        ],
        'coolers'              => [
            'title'       => 'Название',
            'description' => 'Описание',
            'power'       => 'Рассеиваемая мощность',
            'chipset'     => 'Минимальные обороты',
            'form'        => 'Максимальные обороты',
            'vendor_id'   => 'Производитель',
        ],
        'storages'             => [
            'title'              => 'Название',
            'description'        => 'Описание',
            'reading_rate'       => 'Скорость чтения',
            'recording_rate'     => 'Скорость записи',
            'max_resource'       => 'Ресурс записи',
            'memory_capacity_id' => 'Вместимость памяти',
            'vendor_id'          => 'Производитель',
        ],
        'random_access_memory' => [
            'title'                               => 'Название',
            'description'                         => 'Описание',
            'count_of_modules'                    => 'Количество модулей',
            'frequency_of_random_access_memories' => 'Частота',
            'type_of_memory_id'                   => 'Тип памяти',
            'memory_capacity_id'                  => 'Вместимость памяти',
            'vendor_id'                           => 'Производитель',
        ],
        'videocards'           => [
            'title'                => 'Название',
            'description'          => 'Описание',
            'max_frequency'        => 'Максимальная частота',
            'microarchitecture_id' => 'Архитектура',
            'express_version_id'   => 'Версия PCI-E',
            'type_of_memory_id'    => 'Тип памяти',
            'memory_capacity_id'   => 'Вместимость памяти',
            'vendor_id'            => 'Производитель',
        ],
        'psu'                  => [
            'title'       => 'Название',
            'description' => 'Описание',
            'power'       => 'Мощность',
            'form_id'     => 'Форм-фактор',
            'vendor_id'   => 'Производитель',
        ], 'cases' => [
            'title'       => 'Название',
            'description' => 'Описание',
            'form_id'     => 'Форм-фактор',
            'vendor_id'   => 'Производитель',
        ],
    ],
];
